---
title: 'Homework #4'
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Your submission should include both code and well-formatted explanation (not just R comments) and is expected to be reproducible. You may decide for yourself what reproducible file format do you use. 
*Please post on Ed Discussion (accessible in bCourses) for technical questions.*

For this homework, submit the following files on bCourses:

- A report including your answers/discussion for the HW questions.

- A separate R script for the Shiny app in Question 2.


# Questions

1. Create a function to aggregate a data frame by group. The function should accept the following arguments: A data frame; a character scalar specifying the name of the column to be aggregated; a character scalar for the group by column; and a function specifying the aggregator function (could be `mean` or `median`, say). An example call is `MyFun(gapminder, "lifeExp", "country", mean)`, which will return a data frame with two columns, country and the corresponding mean life expectancy. Make sure to include some unit tests for correctness. 

1. Write a Shiny app for visualizing the `gapminder::gapminder` dataset. The app will let the users visualize one column grouped by another column. For example, when visualizing life expectancy grouped by continent, a side-by-side histogram can be used, showing one histogram per continent. The user will select a column to visualize, and another column as the group by column (check out the examples in `?selectInput`). The column being visualized can be either numeric or categorical, and the group by column can only be categorical. Your app should automatically choose an appropriate geom depending on the user inputs. Please include the shiny app code in a separate R script.

1. Look at [two pieces of caveats in visualization (summarized by Jan Holtz)](https://www.data-to-viz.com/caveats.html) that you did not previously know. Find appropriate dataset(s) and implement a bad and a good visualization for each caveat.
